homeassistant:
  name: Home
  latitude: 58.290543
  longitude: 12.341817
  elevation: 49
  unit_system: metric
  time_zone: Europe/Stockholm
  customize: !include_dir_merge_named includes/customize
  customize_glob: !include_dir_merge_named includes/customize_glob

http:
  api_password: !secret http_password
  base_url: !secret http_base_url

verisure:
  username: !secret verisure_email
  password: !secret verisure_password

recorder:
  db_url: !secret db_url
  purge_days: 60

frontend:
updater:
ios:
#discovery:
conversation:
history:
sun:
config:

sensor: !include_dir_merge_list includes/sensors
automation: !include_dir_merge_list includes/automations
zone: !include_dir_list includes/zones
script: !include_dir_merge_named includes/scripts
switch: !include includes/standalonefiles/switch.yaml
group: !include_dir_merge_named includes/groups
input_slider: !include includes/standalonefiles/input_slider.yaml
input_select: !include_dir_merge_named includes/input_select
shell_command: !include_dir_merge_named includes/shell_commands

#  Plain import | enabled
logger: !include includes/standalonefiles/logger.yaml
device_tracker: !include includes/standalonefiles/device_tracker.yaml
panel_iframe: !include includes/standalonefiles/panel_iframe.yaml
mqtt: !include includes/standalonefiles/mqtt.yaml
zwave: !include includes/standalonefiles/zwave.yaml
camera: !include includes/standalonefiles/camera.yaml
notify: !include includes/standalonefiles/notify.yaml
media_player: !include includes/standalonefiles/media_player.yaml
logbook: !include includes/standalonefiles/logbook.yaml

